#ifndef _gpio_h
#define _gpio_h

#ifndef  __IO_Map_H
#include  "IO_Map.h"
#endif

#define REV_B0

#ifdef REV_A0
// ***** Object module define *****
#define LED8_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D0_MASK;
#define LED8_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D0_MASK;
#define LED8_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D0_MASK;
#define LED8_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D0_MASK)

#define LED7_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D1_MASK;
#define LED7_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D1_MASK;
#define LED7_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D1_MASK;
#define LED7_STATUS !(GPIO_B_DATA &   GPIO_A_DATA_D1_MASK)

#define LED6_ON       GPIO_B_DATA &=~ GPIO_B_DATA_D8_MASK;
#define LED6_OFF      GPIO_B_DATA |=  GPIO_B_DATA_D8_MASK;
#define LED6_TOGGLE   GPIO_B_DATA ^=  GPIO_B_DATA_D8_MASK;
#define LED6_STATUS !(GPIO_B_DATA &   GPIO_B_DATA_D8_MASK)

#define LED5_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D3_MASK;
#define LED5_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D3_MASK;
#define LED5_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D3_MASK;
#define LED5_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D3_MASK)

#define LED4_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D2_MASK;
#define LED4_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D2_MASK;
#define LED4_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D2_MASK;
#define LED4_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D2_MASK)

#define LED3_ON      GPIO_B_DATA &=~ GPIO_B_DATA_D9_MASK;
#define LED3_OFF      GPIO_B_DATA |=  GPIO_B_DATA_D9_MASK;
#define LED3_TOGGLE   GPIO_B_DATA ^=  GPIO_B_DATA_D9_MASK;
#define LED3_STATUS !(GPIO_B_DATA &   GPIO_B_DATA_D9_MASK)

#define LED2_ON       GPIO_A_DATA &=~ GPIO_A_DATA_D14_MASK;
#define LED2_OFF      GPIO_A_DATA |=  GPIO_A_DATA_D14_MASK;
#define LED2_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D14_MASK;
#define LED2_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D14_MASK)

#define LED1_ON       GPIO_A_DATA &=~ GPIO_A_DATA_D13_MASK;
#define LED1_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D13_MASK;
#define LED1_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D13_MASK;
#define LED1_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D13_MASK)

#define SW1_STATUS !(GPIO_B_DATA &   GPIO_B_DATA_D1_MASK)
#define SW2_STATUS !(GPIO_B_DATA &   GPIO_B_DATA_D5_MASK)
#define SW3_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D9_MASK)
#define SW4_STATUS !(GPIO_B_DATA &   GPIO_B_DATA_D10_MASK)
#endif

#ifdef REV_B0
// ***** Object module define *****
#define LED8_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D0_MASK
#define LED8_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D0_MASK
#define LED8_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D0_MASK
#define LED8_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D0_MASK)

#define LED7_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D1_MASK
#define LED7_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D1_MASK
#define LED7_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D1_MASK
#define LED7_STATUS !(GPIO_B_DATA &   GPIO_A_DATA_D1_MASK)

#define LED6_ON       GPIO_A_DATA &=~ GPIO_A_DATA_D4_MASK
#define LED6_OFF      GPIO_A_DATA |=  GPIO_A_DATA_D4_MASK
#define LED6_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D4_MASK
#define LED6_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D4_MASK)

#define LED5_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D3_MASK
#define LED5_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D3_MASK
#define LED5_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D3_MASK
#define LED5_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D3_MASK)

#define LED4_ON 	  GPIO_A_DATA &=~ GPIO_A_DATA_D2_MASK
#define LED4_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D2_MASK
#define LED4_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D2_MASK
#define LED4_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D2_MASK)

#define LED3_ON       GPIO_A_DATA &=~ GPIO_A_DATA_D5_MASK
#define LED3_OFF      GPIO_A_DATA |=  GPIO_A_DATA_D5_MASK
#define LED3_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D5_MASK
#define LED3_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D5_MASK)

#define LED2_ON       GPIO_A_DATA &=~ GPIO_A_DATA_D10_MASK
#define LED2_OFF      GPIO_A_DATA |=  GPIO_A_DATA_D10_MASK
#define LED2_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D10_MASK
#define LED2_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D10_MASK)

#define LED1_ON       GPIO_A_DATA &=~ GPIO_A_DATA_D6_MASK
#define LED1_OFF 	  GPIO_A_DATA |=  GPIO_A_DATA_D6_MASK
#define LED1_TOGGLE   GPIO_A_DATA ^=  GPIO_A_DATA_D6_MASK
#define LED1_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D6_MASK)

#define SW1_STATUS !(GPIO_C_DATA &   GPIO_C_DATA_D15_MASK)
#define SW2_STATUS !(GPIO_C_DATA &   GPIO_C_DATA_D14_MASK)
#define SW3_STATUS !(GPIO_B_DATA &   GPIO_B_DATA_D5_MASK)
#define SW4_STATUS !(GPIO_A_DATA &   GPIO_A_DATA_D9_MASK)
#endif


//***** External Declaration *****
void uDSC_GPIO_Init();
#ifdef GPIO_INTERRUPT
void isrGPIO();
void uDSC_SW1_Isr();
void uDSC_SW2_Isr();
void uDSC_SW3_Isr();
void uDSC_SW4_Isr();
#endif

#endif    