#include "gpio.h"

void uDSC_GPIO_Init()
{
#ifdef REV_A0
	// SW & LED control
	GPIO_A_PEREN &=~ (GPIO_A_PEREN_PE0_MASK + GPIO_A_PEREN_PE1_MASK + GPIO_A_PEREN_PE2_MASK + GPIO_A_PEREN_PE3_MASK + GPIO_A_PEREN_PE9_MASK + GPIO_A_PEREN_PE13_MASK + GPIO_A_PEREN_PE14_MASK);
    GPIO_B_PEREN &=~ (GPIO_B_PEREN_PE1_MASK + GPIO_B_PEREN_PE5_MASK + GPIO_B_PEREN_PE8_MASK + GPIO_B_PEREN_PE9_MASK + GPIO_B_PEREN_PE10_MASK);

	// LED outputs
	GPIO_A_DDIR |= (GPIO_A_DDIR_DD0_MASK + GPIO_A_DDIR_DD1_MASK + GPIO_A_DDIR_DD2_MASK + GPIO_A_DDIR_DD3_MASK + GPIO_A_DDIR_DD13_MASK + GPIO_A_DDIR_DD14_MASK);
	GPIO_B_DDIR |= (GPIO_B_DDIR_DD8_MASK + GPIO_B_DDIR_DD9_MASK);

    // SW Inputs
    GPIO_A_DDIR &=~ (GPIO_A_DDIR_DD9_MASK);
    GPIO_B_DDIR &=~ (GPIO_B_DDIR_DD1_MASK + GPIO_B_DDIR_DD5_MASK + GPIO_B_DDIR_DD10_MASK);

#ifdef GPIO_INTERRUPT
	INTC_IPR2 |= (INTC_IPR2_GPIO_A_IPL0_MASK + INTC_IPR2_GPIO_A_IPL1_MASK);
	INTC_IPR2 |= (INTC_IPR2_GPIO_B_IPL0_MASK + INTC_IPR2_GPIO_B_IPL1_MASK);
	GPIO_A_IEN |= GPIO_A_IEN_IEN9_MASK;	
	GPIO_B_IEN |= (GPIO_B_IEN_IEN1_MASK+GPIO_B_IEN_IEN5_MASK+GPIO_B_IEN_IEN10_MASK);
#endif    
#endif

#ifdef REV_B0
	// SW & LED control
	GPIO_A_PEREN &=~ (GPIO_A_PEREN_PE0_MASK + GPIO_A_PEREN_PE1_MASK + GPIO_A_PEREN_PE2_MASK +
	                  GPIO_A_PEREN_PE3_MASK + GPIO_A_PEREN_PE4_MASK + GPIO_A_PEREN_PE5_MASK + 
	                  GPIO_A_PEREN_PE6_MASK + GPIO_A_PEREN_PE9_MASK + GPIO_A_PEREN_PE10_MASK);
	                  
    GPIO_B_PEREN &=~ GPIO_B_PEREN_PE5_MASK;
    GPIO_C_PEREN &=~ (GPIO_C_PEREN_PE14_MASK + GPIO_C_PEREN_PE15_MASK);    

	// LED outputs
	GPIO_A_DDIR |= (GPIO_A_DDIR_DD0_MASK + GPIO_A_DDIR_DD1_MASK + GPIO_A_DDIR_DD2_MASK + 
	                GPIO_A_DDIR_DD3_MASK + GPIO_A_DDIR_DD4_MASK + GPIO_A_DDIR_DD5_MASK +
	                GPIO_A_DDIR_DD6_MASK + GPIO_A_DDIR_DD10_MASK);


    // SW Inputs
    GPIO_A_DDIR &=~ GPIO_A_DDIR_DD9_MASK;
    GPIO_B_DDIR &=~ GPIO_B_DDIR_DD5_MASK;
    GPIO_C_DDIR &=~ (GPIO_C_DDIR_DD14_MASK + GPIO_C_DDIR_DD15_MASK);

#ifdef GPIO_INTERRUPT
	INTC_IPR2 |= (INTC_IPR2_GPIO_A_IPL0_MASK + INTC_IPR2_GPIO_A_IPL1_MASK);
	INTC_IPR2 |= (INTC_IPR2_GPIO_B_IPL0_MASK + INTC_IPR2_GPIO_B_IPL1_MASK);
	INTC_IPR2 |= (INTC_IPR2_GPIO_C_IPL0_MASK + INTC_IPR2_GPIO_C_IPL1_MASK);
	GPIO_A_IEN |= GPIO_A_IEN_IEN9_MASK;	
	GPIO_B_IEN |= GPIO_B_IEN_IEN5_MASK;
	GPIO_C_IEN |= (GPIO_C_IEN_IEN14_MASK + GPIO_C_IEN_IEN15_MASK);
#endif    
#endif


    LED1_OFF;
	LED2_OFF;
	LED3_OFF;
	LED4_OFF;
	LED5_OFF;
	LED6_OFF;
	LED7_OFF;
	LED8_OFF;  
}




//#ifdef GPIO_INTERRUPT 
#pragma interrupt
void isrGPIO()
{
	if (GPIO_C_IPEND & GPIO_C_IPEND_IP15_MASK) 
	{
		uDSC_SW1_Isr();
		GPIO_C_IEDGE |= GPIO_C_IEDGE_IES15_MASK;
	}

	if (GPIO_C_IPEND & GPIO_C_IPEND_IP14_MASK) 
	{
		uDSC_SW2_Isr();
		GPIO_C_IEDGE |= GPIO_C_IEDGE_IES14_MASK;
	}
	if (GPIO_B_IPEND & GPIO_B_IPEND_IP5_MASK) 
	{
		uDSC_SW3_Isr();
		GPIO_B_IEDGE |= GPIO_B_IEDGE_IES5_MASK;
	}
	if (GPIO_A_IPEND & GPIO_A_IPEND_IP9_MASK) 
	{
		uDSC_SW4_Isr();
		GPIO_A_IEDGE |= GPIO_A_IEDGE_IES9_MASK;
	}
}
//#endif